In [3]:
import numpy as np
import pandas as pd

In [5]:
ipl18 = pd.DataFrame({'Team': ['SRH', 'CSK', 'KKR', 'RR', 'MI', 'RCB', 'KXIP', 'DD'],
                         'Matches': [14, 14, 14, 14, 14, 14, 14, 14],
                         'Won': [9, 9, 8, 7, 6, 6, 6, 5],
                         'Lost': [5, 5, 6, 7, 8, 8, 8, 9],
                         'Tied': [0, 0, 0, 0, 0, 0, 0, 0],
                         'N/R': [0, 0, 0, 0, 0, 0, 0, 0],
                         'Points': [18, 18, 16, 14, 12, 12, 12, 10],
                         'NRR': [0.284, 0.253, -0.070, -0.250, 0.317, 0.129, -0.502, -0.222],
                         'For': [2230, 2488, 2363, 2130, 2380, 2322, 2210, 2297],
                         'Against': [2193, 2433, 2425, 2141, 2282, 2383, 2259, 2304]},
                         index = range(1,9)
                    )

ipl18

   Against   For  Lost  Matches  N/R    NRR  Points  Team  Tied  Won
1     2193  2230     5       14    0  0.284      18   SRH     0    9
2     2433  2488     5       14    0  0.253      18   CSK     0    9
3     2425  2363     6       14    0 -0.070      16   KKR     0    8
4     2141  2130     7       14    0 -0.250      14    RR     0    7
5     2282  2380     8       14    0  0.317      12    MI     0    6
6     2383  2322     8       14    0  0.129      12   RCB     0    6
7     2259  2210     8       14    0 -0.502      12  KXIP     0    6
8     2304  2297     9       14    0 -0.222      10    DD     0    5

In [6]:
ipl17 = pd.DataFrame({'Team': ['MI', 'RPS', 'SRH', 'KKR', 'KXIP', 'DD', 'GL', 'RCB'],
                         'Matches': [14, 14, 14, 14, 14, 14, 14, 14],
                         'Won': [10, 9, 8, 8, 7, 6, 4, 3],
                         'Lost': [4, 5, 5, 6, 7, 8, 10, 10],
                         'Tied': [0, 0, 0, 0, 0, 0, 0, 0],
                         'N/R': [0, 0, 1, 0, 0, 0, 0, 1],
                         'Points': [20, 18, 17, 16, 14, 12, 8, 7],
                         'NRR': [0.784, 0.176, 0.469, 0.641, 0.123, -0.512, -0.412, -1.299],
                         'For': [2407, 2180, 2221, 2329, 2207, 2219, 2406, 1845],
                         'Against': [2242, 2165, 2118, 2300, 2229, 2255, 2472, 2033]},
                         index = range(1,9)
                    )

ipl17

   Against   For  Lost  Matches  N/R    NRR  Points  Team  Tied  Won
1     2242  2407     4       14    0  0.784      20    MI     0   10
2     2165  2180     5       14    0  0.176      18   RPS     0    9
3     2118  2221     5       14    1  0.469      17   SRH     0    8
4     2300  2329     6       14    0  0.641      16   KKR     0    8
5     2229  2207     7       14    0  0.123      14  KXIP     0    7
6     2255  2219     8       14    0 -0.512      12    DD     0    6
7     2472  2406    10       14    0 -0.412       8    GL     0    4
8     2033  1845    10       14    1 -1.299       7   RCB     0    3

In [13]:
ipl18w = ipl18.loc[(ipl18.NRR > 0.0) & (ipl18.For > ipl18.Against), ['Team', 'NRR', 'For', 'Against']]
print(ipl18w)

  Team    NRR   For  Against
1  SRH  0.284  2230     2193
2  CSK  0.253  2488     2433
5   MI  0.317  2380     2282

In [28]:
ipl18.set_index('Team', inplace=True)
ipl17.set_index('Team', inplace=True)

KeyError: 'Team'

In [30]:
tot = ipl18.add(ipl17, fill_value=0)

In [33]:
tot = tot.loc[(tot.Points > 25)]
tot= tot.assign(wp=tot.Won*100/tot.Matches)
print(tot.sort_values(by=['wp']).head(1)
print(tot)

      Against     For  Lost  Matches  N/R    NRR  Points  Tied   Won  \
Team
KKR    4725.0  4692.0  12.0     28.0  0.0  0.571    32.0   0.0  16.0
KXIP   4488.0  4417.0  15.0     28.0  0.0 -0.379    26.0   0.0  13.0
MI     4524.0  4787.0  12.0     28.0  0.0  1.101    32.0   0.0  16.0
SRH    4311.0  4451.0  10.0     28.0  1.0  0.753    35.0   0.0  17.0

             wp
Team
KKR   57.142857
KXIP  46.428571
MI    57.142857
SRH   60.714286

In [36]:
print(tot.sort_values(by=['wp'], ascending=False).head(1))

      Against     For  Lost  Matches  N/R    NRR  Points  Tied   Won  \
Team
SRH    4311.0  4451.0  10.0     28.0  1.0  0.753    35.0   0.0  17.0

             wp
Team
SRH   60.714286